---
apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNfYWRtaW4K
  POSTGRES_PASSWORD: UGFzc3cwcmQhCg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  strategy: {}
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: postgres:14
        name: postgres
        ports:
        - containerPort: 5432
        envFrom:
          - secretRef:
              name: db-secrets
        env:
          - name: POSTGRES_DB
            value: postgres
          - name: PGDATa
            value: "/data/postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 8001
    targetPort: 5432
  selector:
    app: db
